Homepage back
wolox-training/ab-android pull request #9
Opened 2019-02-22 21:12 UTC by alejandrobodichon

### Summary
The news are loaded in the background from a REST server. A endlessScrollListener has been added in the recyclerview.
### Screenshot

![image](https://user-images.githubusercontent.com/28766880/53271479-55f7a780-36cd-11e9-9ddf-e689def1d090.png)

### Trello card
https://trello.com/c/arumdQt3/11-u5-home-page-backend-news

2019-02-22 21:18 UTC, lmiotti commented on app/src/main/java/ar/com/wolox/android/example/TrainingApplication.java
> +        ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
What is this?

2019-02-22 21:19 UTC, lmiotti commented on app/src/main/java/ar/com/wolox/android/example/ui/training/homePage/news/EndlessRecyclerViewScrollListener.kt
> +    constructor(visibleThreshold: Int, layoutManager: GridLayoutManager): this(visibleThreshold) {
We can delete the constructors that you are not using

2019-02-22 21:20 UTC, lmiotti commented on app/src/main/java/ar/com/wolox/android/example/ui/training/login/LoginFragment.java
> +
Erase this empty line

2019-02-22 21:21 UTC, lmiotti commented on app/src/main/res/layout/recycler_news.xml
> +        fresco:fadeDuration="500"
Put this on integer file

2019-02-22 21:21 UTC, lmiotti commented on app/src/main/res/layout/recycler_news.xml
> +        fresco:progressBarAutoRotateInterval="1000"
same as above

2019-02-22 21:22 UTC, lmiotti commented on app/src/main/java/ar/com/wolox/android/example/ui/training/homePage/news/NewsPresenter.kt
>      fun loadNews(): MutableList<News> {
Add an empty line above

2019-02-22 21:24 UTC, lmiotti commented on app/src/main/java/ar/com/wolox/android/example/ui/training/homePage/news/NewsPresenter.kt
>      fun loadNews(): MutableList<News> {
As discussed on private, follow the MVP model

2019-02-22 21:24 UTC, lmiotti requested changes
Few changed to be done and we finish  training. Come on!

2019-02-25 14:18 UTC, lmiotti approved these changes
You have finished training!!! Congratulations!

![giphy](https://user-images.githubusercontent.com/36635668/53343329-e6f99900-38ee-11e9-9f84-5939fff5af54.gif)

2019-02-25 16:52 UTC, dylan-muszel approved these changes
You have finished the training, congratulations! Good luck with the project!

![](https://media3.giphy.com/media/hr6p5UHdDn8RO/giphy.gif)

2019-02-27 19:22 UTC, merged